"""
Bundle markdown/*.md into files/content.js so the project pages need no fetch().

    python bundle_markdown.py

The GitHub Pages workflow runs this before publishing; run it locally to preview the
write-ups when opening the site straight from disk (file://).
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent
content = {p.stem: p.read_text(encoding="utf-8") for p in sorted((ROOT / "markdown").glob("*.md"))}
out = "// Generated by bundle_markdown.py from markdown/*.md - do not edit by hand.\n"
out += "window.SITE_CONTENT = " + json.dumps(content, ensure_ascii=False, indent=2) + ";\n"
(ROOT / "files" / "content.js").write_text(out, encoding="utf-8")
print(f"files/content.js: {', '.join(content)}")
